# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request_target:
    types: [opened, synchronize, labeled, unlabeled, reopened]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Extract Messages
      uses: actions/setup-node@v3
      with:
        registry-url: 'https://npm.pkg.github.com'
        node-version-file: '.node-version'
        cache: 'npm'

    - run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: git config user.name "github-actions[bot]"
    - run: git config user.email "github-actions[bot]@users.noreply.github.com"
    - run: npm run extract:messages
    - run: git add src/config/intl/en-US/main.json
    - run: git commit -m "🤖 extracted messages"
    - run: git push
